proper lint in cpp

diff --git a/.github/workflows/c-cpp-lint.yml b/.github/workflows/c-cpp-lint.yml
--- a/.github/workflows/c-cpp-lint.yml
+++ b/.github/workflows/c-cpp-lint.yml
@@ -24,7 +24,7 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
 
       - name: Install build essentials (if needed)
         run: |
@@ -54,3 +54,22 @@ jobs:
               return 1
             fi
           done
+
+  cpp-linter:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cpp-linter/cpp-linter-action@main
+        id: linter
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+          files-changed-only: false
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed != 0
+        run: |
+          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+          exit 1
